### ISSUE TITLE
Add support for resource group config

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#341]
This feature request is to add support for configuring resource group setting.

https://docs.gitlab.com/ee/api/resource_groups.html

Unlike any other gitlab setting, it's only manageable through API as of right now. They don't even have a UI for it yet.

Anyways, it'd be nice to be able to manage this through gitlabform as it's an important settings related managing code deployment using gitlab ci.

**Comment by ep-linden** [comment]
Since we can only change the process mode of a resource group through the API, it will be beneficial for GitLabForm to handle it.

In terms of implementation. I'm thinking we can place the `resource_group` API in `projects.py` (the base class). There is only a `GET` and a `PUT` request, so it should be fairly a simple add to GitLabForm.

@gdubicki I can look into implementing this if we get the green light.

**Comment by gdubicki** [comment]
Hi! Of course we are very open to PRs with this feature. :)

**Comment by gdubicki** [comment]
Released in [v3.1.0](https://github.com/gitlabform/gitlabform/releases/tag/v3.1.0) a moment ago.
