### ISSUE TITLE
Link in Docker Hub is broken (404)

### ISSUE THREAD

**Issue by trzeciakp** [gitlabform/gitlabform#383]
**Describe the bug**

Link in the description in [docker hub](https://hub.docker.com/r/egnyte/gitlabform):

points to:

https://github.com/gitlabform/gitlabform/pkgs/container/gitlabform

I get 404 when I open it. Perhaps it should point to:

https://github.com/gdubicki/gitlabform/pkgs/container/gitlabform

**GitLabForm version**

N/A

**GitLab version**

N/A

**Comment by gdubicki** [comment]
Hi @trzeciakp!

The https://github.com/gitlabform/gitlabform/pkgs/container/gitlabform link was correct but I forgot to make it public and didn't notice that because I was logged in to Github... Thanks for reporting it!

A few days ago [we moved](https://github.com/gitlabform/gitlabform/commit/d15715a5b42ace2b7539bc3fcdf6b8dfedcf6082) this project under the new gitlabform organisation. Because of that the URL of the Docker image has changed to also be under gitlabform/gitlabform - https://github.com/gitlabform/gitlabform/pkgs/container/gitlabform. Unfortunately GitHub doesn't redirect such links (the way they redirect links to repos, for example after they are moved).

In a few days I will upload a package to the old address of https://github.com/gdubicki/gitlabform/pkgs/container/gitlabform with an image that will just show a message that the image address has changed, like I did for the first image location, https://hub.docker.com/r/egnyte/gitlabform. After a month or so I will delete both of the old images permanently.
