### ISSUE TITLE
Add retry feature

### ISSUE THREAD

**Issue by admantium-sg** [gitlabform/gitlabform#709]
Hello,

we are using gitlabform in an on-premise GitLab installation with about 600 projects. Today we noticed that randomly, different projects can not be processed.

E.g.

Run 1

```
:: # of projects failed: 2 
:: Failed project 102: REDACTED
:: Failed project 105: REDACTED
```

Run 2

```
:: # of projects failed: 1 
:: Failed project 178: REDACTED
```

I would like to see a configurable retry option.

**Comment by amimas** [comment]
Based on this thread, it seems there is already built-in retry logic when the API call fails with 500 server error.

https://github.com/gitlabform/gitlabform/issues/531

Not sure what the issue is in your case. Did you try running with `--debug` or `--verbose` enabled? That might reveal the source of the issue. If it's a legitimate issue, the retry won't really solve it, right?

I know debug/verbose logs can be annoying when things are working fine because they clutter the output. I always thought it'd be nice if the tool would produce debug/verbose log as a file instead of stdout. That way when things go wrong, we can simply inspect the log file.

**Comment by admantium-sg** [comment]
Clone of #531
