### ISSUE TITLE
Detect configuration syntax errors

### ISSUE THREAD

**Issue by gdubicki** [gitlabform/gitlabform#81]
Because of the "raw parameters passing" design concept applied in this app you cannot detect all kinds of syntax errors with a reasonable amount of development effort until you try to apply the config.

But we should be able to detect some key syntax problems to prevent users from having doubts like mentioned [here](https://github.com/egnyte/gitlabform/issues/68#issue-521491527):

> I could just be using it wrong (although I've tried moving the key "approvers" under "approvals" and this didn't work either).

Let's fix this! Ideas on how to do it are very welcome. :) I am thinking about generating the effective config and then checking it against some YAML-schema thing if something like that exists.

**Comment by gdubicki** [comment]
We can start by checking if the the config is a valid YAML and provide friendly error messages with github.com/adrienverge/yamllint using a method mentioned in https://github.com/adrienverge/yamllint/issues/112 .

**Comment by gdubicki** [comment]
We have moved this forward a bit in [v2.9.0](https://github.com/gdubicki/gitlabform/releases/tag/v2.9.0) thanks to switching the YAML parser from PyYAML to ruamel.yaml that by default [disallows duplicate dict keys](https://yaml.readthedocs.io/en/latest/api.html#duplicate-keys). It is also wrapped in yamlpath that [promises to provide more helpful error messages](https://github.com/wwkimball/yamlpath/blob/master/yamlpath/common/parsers.py#L109-L112).

I think that the next step will be switch to YAML 1.2 for configuration in gitlabform v3.

**Comment by armingerten** [comment]
In order to move this forward, it could be considered to provide a [JSON Schema](https://json-schema.org/) that describes the basic structure of the `config.yml` file. Providing such schema has multiple advantages:

- The schema can be used when running `gitlabform` to validate whether the `config.yml` is malformed. Libraries like [yamale](https://pypi.org/project/yamale/) provide an implementation to validate YAML using JSON Schema (Current PyPi [download count / day](https://pypistats.org/packages/yamale) is ~10.000).
- The schema can be integrated into popular IDEs (IDEA, VSCode, etc.) and used for validation, documentation and code completion.
- When added properly to [schemastore.org](https://www.schemastore.org), IDEs automatically detect the schema and offer afore mentioned validation, documentation and code completion out of the box.

WDYT?

**Comment by gdubicki** [comment]
Closing in favor of the newer #499.
